/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2super;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Nicolas Mendez, Antonio Yibirin
 */
public class carga extends javax.swing.JFrame {

    /**
     * Creates new form carga
     */
    public static Controlador controlador = new Controlador();
    public static final String DATA_RUTA = "data/investigaciones_db.txt";
    
    public carga() {
        initComponents();
        File f = new File(DATA_RUTA);
        if (f.exists() && f.length() > 0) {
            try {
                controlador.cargarDesdeArchivo(DATA_RUTA);
                JOptionPane.showMessageDialog(this, "Datos cargados desde: " + DATA_RUTA);
            } catch (Exception ex) {
                // No fatal: seguir con ejecución, pero avisar al usuario
                JOptionPane.showMessageDialog(this,
                        "No se pudieron cargar los datos guardados.\n" + ex.getMessage(),
                        "Aviso", JOptionPane.WARNING_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            // No hay archivo guardado — opción: crear carpeta data para futuros guardados
            File dir = new File("data");
            if (!dir.exists()) dir.mkdirs();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCarga = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("¡Bienvenido!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        btnCarga.setText("Cargar Archivo con articulos (txt)");
        btnCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel2.setText("Nicolas Mendez y Antonio Yibirin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Evento del botón "Cargar Archivo con articulos".
     * 
     * Abre un selector de archivos y permite al usuario elegir un archivo .txt
     * con investigaciones en el formato requerido.
     *
     * @param evt evento generado al hacer clic en el botón
     */
    private void btnCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileFilter(new FileNameExtensionFilter("Archivos de texto (.txt)", "txt")); // Opcional recomendado

        int resultado = selector.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            File archivo = selector.getSelectedFile();
            boolean ok = controlador.cargarArchivo(archivo.getAbsolutePath());

            if (ok) {
                JOptionPane.showMessageDialog(this, "Archivo cargado correctamente.");

                // Solo abrir ventana Home si todo fue bien
                home pantalla = new home();
                pantalla.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, 
                        "Error cargando el archivo.\nVerifique el formato del archivo.",
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);
            }

        } else {
            // Usuario canceló, no hacemos nada.
            JOptionPane.showMessageDialog(this, "Carga cancelada.");
        }
    }//GEN-LAST:event_btnCargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
