/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2super;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicolas Mendez, Antonio Yibirin
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    
    private Controlador controlador = carga.controlador;
    
    public home() {
        initComponents();
        llenarCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        SelectAutor = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        inputBuscar = new javax.swing.JTextField();
        btnBuscarAutor = new javax.swing.JButton();
        btnBuscarClave = new javax.swing.JButton();
        btnListarClaves = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pantalla = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        SelectResumen = new javax.swing.JComboBox<>();
        btnAnalizarResumen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 20, 500));

        jPanel1.add(SelectAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 250, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 250, -1));
        jPanel1.add(inputBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 250, -1));

        btnBuscarAutor.setText("Buscar por Autor");
        btnBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAutorActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 250, -1));

        btnBuscarClave.setText("Buscar");
        btnBuscarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 250, -1));

        btnListarClaves.setText("Listar palabras claves");
        btnListarClaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarClavesActionPerformed(evt);
            }
        });
        jPanel1.add(btnListarClaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 250, -1));

        Pantalla.setColumns(20);
        Pantalla.setRows(5);
        jScrollPane1.setViewportView(Pantalla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 20, 420, 510));

        jLabel1.setText("Buscar por palabra clave:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jPanel1.add(SelectResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, -1));

        btnAnalizarResumen.setText("Analizar resumen");
        btnAnalizarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarResumenActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnalizarResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Llena los ComboBox:     * 
     * Se asegura de que existan autores e investigaciones antes de agregarlos.
     */
    private void llenarCombos() {

        // Limpiar combos
        //SelectAutor.removeAllItems();
        //SelectResumen.removeAllItems();

        // Llenar autores desde el AVL
        ListaEnlazada<String> autores = controlador.listarAutores();

        if (autores != null) {
            for (int i = 0; i < autores.tamano(); i++) {
                String autor = autores.obtener(i);
                SelectAutor.addItem(autor);
            }
        }
    
        ListaEnlazada<Investigacion> investigaciones = controlador.obtenerTodasLasInvestigaciones(); 

        if (investigaciones != null) {
            for (int i = 0; i < investigaciones.tamano(); i++) {
                SelectResumen.addItem(investigaciones.obtener(i).getTitulo());
            }
        }
    }
    
    /**
     * Acción del botón "Analizar resumen".
     * Obtiene el título seleccionado, recupera la investigación correspondiente y analiza el contenido del cuerpo del resumen.
     * 
     * Muestra en la pantalla las palabras más frecuentes encontradas.
     *
     * @param evt evento generado por el botón
     */
    private void btnAnalizarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarResumenActionPerformed
        if (SelectResumen.getItemCount() == 0) {
            Pantalla.setText("No hay investigaciones cargadas.");
            return;
        }

        String titulo = (String) SelectResumen.getSelectedItem();
        Investigacion inv = controlador.buscarPorTitulo(titulo);

        if (inv == null) {
            Pantalla.setText("No se encontró investigación");
            return;
        }

        ListaEnlazada<PalabraFrecuencia> lista =
                controlador.analizarResumen(inv.getCuerpo());

        Pantalla.setText("TOP PALABRAS DEL RESUMEN:\n\n");
        for (int i = 0; i < lista.tamano(); i++) {
            PalabraFrecuencia pf = lista.obtener(i);
            Pantalla.append(pf.getPalabra() + " : " + pf.getFrecuencia() + "\n");
        }
    }//GEN-LAST:event_btnAnalizarResumenActionPerformed

    /**
     * Acción del botón "Buscar" para palabras clave.
     * Realiza una búsqueda de investigaciones que contengan la palabra ingresada.
     * 
     * Si no encuentra coincidencias se muestra un mensaje correspondiente.
     *
     * @param evt evento generado por el botón
     */
    private void btnBuscarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClaveActionPerformed
        String clave = inputBuscar.getText().trim();

        if (clave.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una palabra clave.");
            return;
        }

        ListaEnlazada<Investigacion> lista =
                controlador.buscarPorPalabraClave(clave);

        Pantalla.setText("");

        if (lista == null || lista.tamano() == 0) {
            Pantalla.setText("No se encontraron artículos con esa palabra clave.");
            return;
        }

        for (int i = 0; i < lista.tamano(); i++) {
            Pantalla.append(lista.obtener(i).toString() + "\n\n");
        }
    }//GEN-LAST:event_btnBuscarClaveActionPerformed

    /**
     * Acción del botón "Listar palabras claves".
     * Recupera todas las palabras clave registradas y las muestra ordenadas.
     *
     * @param evt evento generado por el botón
     */
    private void btnListarClavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarClavesActionPerformed
        ListaEnlazada<String> lista = controlador.listarPalabrasClaveOrdenadas();

        Pantalla.setText("PALABRAS CLAVE REGISTRADAS:\n\n");

        for (int i = 0; i < lista.tamano(); i++) {
            Pantalla.append(lista.obtener(i) + "\n");
        }
    }//GEN-LAST:event_btnListarClavesActionPerformed

    /**
     * Acción del botón "Buscar por Autor".
     * Busca todas las investigaciones asociadas al autor seleccionado.
     * 
     * Muestra un mensaje si no existen investigaciones del autor.
     *
     * @param evt evento generado por el botón
     */
    private void btnBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAutorActionPerformed
        if (SelectAutor.getItemCount() == 0) {
            Pantalla.setText("No hay autores registrados.");
            return;
        }

        String autor = (String) SelectAutor.getSelectedItem();

        ListaEnlazada<Investigacion> lista =
                controlador.buscarPorAutor(autor);

        Pantalla.setText("");

        if (lista == null || lista.tamano() == 0) {
            Pantalla.setText("No hay investigaciones de este autor.");
            return;
        }

        for (int i = 0; i < lista.tamano(); i++) {
            Pantalla.append(lista.obtener(i).toString() + "\n\n");
        }
    }//GEN-LAST:event_btnBuscarAutorActionPerformed

    /**
     * Acción del botón "Salir".
     * Guarda los datos actuales mediante el controlador y finaliza la aplicación.
     *
     * @param evt evento generado por el botón
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        try {
            controlador.guardarEnArchivo(carga.DATA_RUTA);
        } catch (Exception ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Pantalla;
    private javax.swing.JComboBox<String> SelectAutor;
    private javax.swing.JComboBox<String> SelectResumen;
    private javax.swing.JButton btnAnalizarResumen;
    private javax.swing.JButton btnBuscarAutor;
    private javax.swing.JButton btnBuscarClave;
    private javax.swing.JButton btnListarClaves;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField inputBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
